redis:
  service:
    version:
      v1: 1.0.0

spring:
  application:
    name: microservice-redis-provider
  # redis配置
  redis:
    host: 172.19.4.81
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
dubbo:
  scan:
    base-packages: com.github.microservice.redis.provider
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 20000
  registry:
    address: zookeeper://172.19.4.81:2181
    simplified: true
  config-center:
    address: zookeeper://172.19.4.81:2181
  metadata-report:
    address: zookeeper://172.19.4.81:2181

