redis:
  service:
    version:
      v1: 1.0.0
spring:
  application:
    name: microservice-redis-provider
  # redis配置
  redis:
    host: 172.19.4.81
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
dubbo:
  scan:
    basePackages: com.github.microservice.redis.api.impl
  protocol:
    name: dubbo
    port: 20880
    serialization: kryo
  provider:
    timeout: 50000
    threads: 500
  consumer:
    timeout: 50000
    retries: 0
  registry:
    address: zookeeper://172.19.4.81:2181
    simplified: true
    file: ${user.home}/.dubbo/${spring.application.name}.cache
  config-center:
    address: zookeeper://172.19.4.81:2181
  metadata-report:
    address: zookeeper://172.19.4.81:2181
