redis:
  service:
    version:
      v1: 1.0.0

spring:
  application:
    name: microservice-web-demo

dubbo:
  scan:
    base-packages: com.github.microservice.redis.provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://172.19.4.81:2181
  metadata-report:
    address: zookeeper://172.19.4.81:2181
  config-center:
    address: zookeeper://172.19.4.81:2181
