redis:
  service:
    version:
      v1: 1.0.0
server:
  port: 8000

spring:
  application:
    name: microservice-web-demo

dubbo:
  registry:
    address: zookeeper://172.19.4.81:2181
    simplified: true
    file: ${user.home}/.dubbo/${spring.application.name}.cache
