redis:
  service:
    version:
      v1: 1.0.0
server:
  port: 8000

spring:
  application:
    name: microservice-web-demo

dubbo:
  scan:
    basePackages: com.github.web.demo.controller
  registry:
    address: zookeeper://172.19.4.81:2181
    simplified: true
    file: ${user.home}/.dubbo/${spring.application.name}.cache
  config-center:
    address: zookeeper://172.19.4.81:2181
  metadata-report:
    address: zookeeper://172.19.4.81:2181
